import { Check, ChevronDown, MapPin } from "lucide-react";
import { motion } from "framer-motion";

import CheckoutField from "./CheckoutField";
import type { NewAddress, SavedAddress } from "./checkout-types";

const emirates = ["Abu Dhabi", "Dubai", "Sharjah", "Ajman", "Umm Al Quwain", "Ras Al Khaimah", "Fujairah"];

type Props = { addresses: SavedAddress[]; mode: "saved" | "new"; selectedAddressId: string; address: NewAddress; saveAddress: boolean; onUseNew: () => void; onSelect: (id: string) => void; onChange: (field: keyof NewAddress, value: string) => void; onSaveAddressChange: (value: boolean) => void };

export default function DeliveryAddressForm({ addresses, mode, selectedAddressId, address, saveAddress, onUseNew, onSelect, onChange, onSaveAddressChange }: Props) {
  const showNew = mode === "new" || !addresses.length;
  return <motion.section initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.4, delay: 0.05 }} className={cardClass}>
    <div className="flex items-center gap-3 border-b border-[var(--primary)]/10 pb-4"><div className="flex h-[40px] w-[40px] items-center justify-center rounded-full bg-[var(--surface)] text-[var(--primary)]"><MapPin size={17} /></div><div><div className="flex items-center gap-2"><span className="text-[8px] font-semibold tracking-[0.15em] text-[var(--accent)]">02</span><h2 className="font-serif text-[20px] font-semibold text-[var(--foreground)] sm:text-[22px]">Delivery Address</h2></div><p className="mt-0.5 text-[9px] text-[var(--foreground)]/40">Where should we deliver your order?</p></div></div>
    {!showNew && <div className="mt-5 grid gap-3">{addresses.map((saved) => <label key={saved.id} className="flex cursor-pointer items-start gap-3 rounded-[13px] border border-[var(--primary)]/12 bg-[var(--background)] px-4 py-3"><input type="radio" name="address" checked={selectedAddressId === saved.id} onChange={() => onSelect(saved.id)} className="sr-only" /><span className={`mt-0.5 flex h-[19px] w-[19px] shrink-0 items-center justify-center rounded-full border ${selectedAddressId === saved.id ? "border-[var(--primary)] bg-[var(--primary)] text-white" : "border-[var(--primary)]/20 bg-white"}`}>{selectedAddressId === saved.id && <Check size={12} />}</span><span className="text-[10px] leading-5 text-[var(--foreground)]/55"><strong className="text-[var(--foreground)]">{saved.label}{saved.isDefault ? " — Default" : ""}</strong><br />{saved.addressLine1}, {saved.area}<br />{saved.city}, {saved.emirate}</span></label>)}<button type="button" onClick={onUseNew} className="w-fit text-[10px] font-semibold text-[var(--primary)] underline underline-offset-4">+ Use a new address</button></div>}
    {showNew && <><div className="mt-5 grid gap-4 sm:grid-cols-2"><CheckoutField label="Recipient Name" required><input value={address.recipientName} onChange={(e) => onChange("recipientName", e.target.value)} required className={inputClass} /></CheckoutField><CheckoutField label="Mobile Number" required><input type="tel" value={address.phone} onChange={(e) => onChange("phone", e.target.value)} required className={inputClass} /></CheckoutField><div className="sm:col-span-2"><CheckoutField label="Address Line 1" required><input value={address.addressLine1} onChange={(e) => onChange("addressLine1", e.target.value)} required className={inputClass} /></CheckoutField></div><div className="sm:col-span-2"><CheckoutField label="Address Line 2"><input value={address.addressLine2} onChange={(e) => onChange("addressLine2", e.target.value)} className={inputClass} /></CheckoutField></div><CheckoutField label="Area" required><input value={address.area} onChange={(e) => onChange("area", e.target.value)} required className={inputClass} /></CheckoutField><CheckoutField label="Emirate" required><div className="relative"><select value={address.emirate} onChange={(e) => onChange("emirate", e.target.value)} required className={selectClass}><option value="">Select Emirate</option>{emirates.map((emirate) => <option key={emirate}>{emirate}</option>)}</select><ChevronDown size={15} className="pointer-events-none absolute right-4 top-1/2 -translate-y-1/2 text-[var(--foreground)]/35" /></div></CheckoutField><CheckoutField label="Address Label" required><select value={address.label} onChange={(e) => onChange("label", e.target.value)} className={selectClass}><option>Home</option><option>Office</option></select></CheckoutField><div className="sm:col-span-2"><CheckoutField label="Delivery Notes"><textarea value={address.notes} onChange={(e) => onChange("notes", e.target.value)} rows={4} className={textareaClass} /></CheckoutField></div></div><label className="mt-5 flex cursor-pointer items-center gap-3"><input type="checkbox" checked={saveAddress} onChange={(e) => onSaveAddressChange(e.target.checked)} className="sr-only" /><span className={`flex h-[19px] w-[19px] items-center justify-center rounded-[5px] border ${saveAddress ? "border-[var(--primary)] bg-[var(--primary)] text-white" : "border-[var(--primary)]/20 bg-white"}`}>{saveAddress && <Check size={12} />}</span><span className="text-[10px] text-[var(--foreground)]/55">Save this address to my account for faster checkout next time</span></label></>}
  </motion.section>;
}

const cardClass = "rounded-[22px] border border-[var(--primary)]/8 bg-white p-4 shadow-[0_10px_40px_rgba(45,32,32,0.04)] sm:rounded-[26px] sm:p-6 lg:p-7";
const inputClass = "h-[50px] w-full rounded-[13px] border border-[var(--primary)]/12 bg-[var(--background)] px-4 text-[10px] text-[var(--foreground)] outline-none focus:border-[var(--primary)]/45 sm:text-[11px]";
const selectClass = "h-[50px] w-full appearance-none rounded-[13px] border border-[var(--primary)]/12 bg-[var(--background)] px-4 pr-10 text-[10px] text-[var(--foreground)] outline-none focus:border-[var(--primary)]/45 sm:text-[11px]";
const textareaClass = "w-full resize-none rounded-[13px] border border-[var(--primary)]/12 bg-[var(--background)] px-4 py-3.5 text-[10px] text-[var(--foreground)] outline-none focus:border-[var(--primary)]/45 sm:text-[11px]";
